### ISSUE TITLE
交流

### ISSUE THREAD

**Issue by wesleyel** [greyishsong/greyishsong.github.io#1]
你好,

我是另一个班来的同学, 你的个人网站令我印象深刻, 可以看出来你非常乐于学习新知识.  现在有一个**中国高校计算机大赛移动应用创新赛**([链接在此](http://www.appcontest.net/2020/index.html))的项目, 我在寻求一些合作. 老实说我也没有`Swift`基础,不过我相信这都可以后期学习, 如果你愿意加入我的话, 欢迎同我联系! 

真诚的,
magicwenli

**Comment by greyishsong** [comment]
你好！

承蒙欣赏，不胜荣幸。不才学浅，只是偶尔发问求索，希冀有所长进。

简单看了看你的repo，非常高兴遇到一个同好者，真心希望能够成为朋友。但是我个人感觉Apple系的`swift`语言与`OS X/iOS`系统绑定太过紧密，对此并不是非常感兴趣；另外我也没有用于搭建Xcode开发环境的Mac OS设备，所以可能不会参加这次比赛。

如果可以的话，希望我们保持联系。无论这次比赛情况如何，愿交流不断。

可以联系greyishsong@qq.com，我一般能够当天内阅读邮件并回复。

真诚的，<br>greyishsong

**Comment by greyishsong** [comment]
> 
> 
> 你好,
> 
> 我是另一个班来的同学, 你的个人网站令我印象深刻, 可以看出来你非常乐于学习新知识. 现在有一个**中国高校计算机大赛移动应用创新赛**([链接在此](http://www.appcontest.net/2020/index.html))的项目, 我在寻求一些合作. 老实说我也没有`Swift`基础,不过我相信这都可以后期学习, 如果你愿意加入我的话, 欢迎同我联系!
> 
> 真诚的,
> magicwenli

你好！

承蒙欣赏，不胜荣幸。不才学浅，只是偶尔发问求索，希冀有所长进。

简单看了看你的repo，非常高兴遇到一个同好者，真心希望能够成为朋友。但是我个人感觉Apple系的`swift`语言与`OS X/iOS`系统绑定太过紧密，对此并不是非常感兴趣；另外我也没有用于搭建Xcode开发环境的Mac OS设备，所以可能不会参加这次比赛。

如果可以的话，希望我们保持联系。无论这次比赛情况如何，愿交流不断。

可以联系greyishsong@qq.com，我一般能够当天内阅读邮件并回复。

真诚的，<br>greyishsong
